# Generated by Django 4.2.5 on 2023-10-29 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateField()),
                ('type_of_record', models.CharField(default="Doctor's Visit", max_length=100)),
                ('medical_notes', models.TextField()),
                ('image', models.ImageField(upload_to='medical_images/')),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
